# Site settings
title: Vino LaMusic
description: Latin DJ & Producer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vino LaMusic
user_description:  Known for his electrifying sets that mesmerize audiences globally, Vino LaMusic doesn't just play music—he crafts immersive experiences that linger long after the night ends.

<iframe style="border: 0; width: 100%; height: 120px;" src="https://bandcamp.com/EmbeddedPlayer/track=2383430009/size=large/bgcol=333333/linkcol=e99708/tracklist=false/artwork=small/transparent=true/" seamless><a href="https://vinolamusic.bandcamp.com/track/adam-port-stryv-move-feat-malachiii-vino-lamusic-remix">Adam Port, Stryv - Move feat. Malachiii  (Vino LaMusic Remix) by Vino LaMusic</a></iframe>


user_title: Latin DJ & Producer
email: info@vinolamusic.com
# twitter_username: lorem_ipsum
instagram_username: vino.lamusic
facebook_username: vinolamusic92
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

