# Site settings
title: Vino LaMusic
description: Latin DJ & Producer
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Vino LaMusic
user_description: Vino LaMusic is a visionary Latin DJ and producer, blending the vibrant sounds of Latin music with modern electronic beats. With years of experience in the industry, Vino La Music is known for creating dynamic sets that captivate audiences around the world.


user_title: Latin DJ & Producer
email: info@vinolamusic.com
# twitter_username: lorem_ipsum
instagram_username: vino.lamusic
facebook_username: vinolamusic92
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

